### ISSUE TITLE
error: no usb devices opened

### ISSUE THREAD

**Issue by qxlsz** [MattIPv4/PyDMXControl#27]
getting this error
```python
In [8]: from PyDMXControl.controllers import uDMXController
   ...:

In [9]: dmx = uDMXController()

Exception in thread Thread-1088:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rjosyula/.dirty/raj/lib/python3.6/site-packages/PyDMXControl/utils/timing/_Ticker.py", line 56, in __ticker__loop
    self.__ticker()
  File "/home/rjosyula/.dirty/raj/lib/python3.6/site-packages/PyDMXControl/utils/timing/_Ticker.py", line 42, in __ticker
    callback()
  File "/home/rjosyula/.dirty/raj/lib/python3.6/site-packages/PyDMXControl/controllers/_uDMXController.py", line 61, in _send_data
    raise e
  File "/home/rjosyula/.dirty/raj/lib/python3.6/site-packages/PyDMXControl/controllers/_uDMXController.py", line 56, in _send_data
    self.__udmx.send_multi_value(1, data)
  File "/home/rjosyula/.dirty/raj/lib/python3.6/site-packages/pyudmx/pyudmx.py", line 149, in send_multi_value
    channel=channel, data_or_length=ba)
  File "/home/rjosyula/.dirty/raj/lib/python3.6/site-packages/pyudmx/pyudmx.py", line 94, in _send_control_message
    raise ValueError("No usb device opened")
ValueError: No usb device opened

In [10]:
```

**Comment by MattIPv4** [comment]
@qxlsz Have you got a uDMX USB to DMX dongle connected to your device?

**Comment by qxlsz** [comment]
Lemme check

**Comment by qxlsz** [comment]
all i have is 
![image](https://user-images.githubusercontent.com/4540836/61557855-2d749f00-aa1a-11e9-8004-60c557a2fcbc.png)

**Comment by qxlsz** [comment]
using this device https://www.enttec.com/product/controls/dmx-usb-interfaces/open-dmx-usb/

**Comment by MattIPv4** [comment]
I don't own an open DMX device yet, so I haven't written a controller for it.
You are absolutely welcome to fork this project, write a new controller that works with open DMX and then PR it :)

**Comment by MattIPv4** [comment]
👋 Sorry for such a late reply to this, but I finally got my hands on an FTDI chip and have now implemented an OpenDMX FTDI controller -- this is currently in master, and will be part of the eventual 2.0.0 release.
