### ISSUE TITLE
Lock down requirements.txt to specific versions

### ISSUE THREAD

**Issue by crscheid** [MattIPv4/PyDMXControl#49]
Running the sample example from a fresh install on Python 3.9 gives the following error:

```
Traceback (most recent call last):
  File "/home/show/showcontroller/tests/test_1.py", line 3, in <module>
    from PyDMXControl.controllers import OpenDMXController
  File "/home/show/showcontroller/scenv/lib/python3.9/site-packages/PyDMXControl/controllers/__init__.py", line 20, in <module>
    from ._Controller import Controller
  File "/home/show/showcontroller/scenv/lib/python3.9/site-packages/PyDMXControl/controllers/_Controller.py", line 20, in <module>
    from ..web import WebController
  File "/home/show/showcontroller/scenv/lib/python3.9/site-packages/PyDMXControl/web/__init__.py", line 20, in <module>
    from ._webController import WebController
  File "/home/show/showcontroller/scenv/lib/python3.9/site-packages/PyDMXControl/web/_webController.py", line 16, in <module>
    from ._routes import routes  # Web Routes
  File "/home/show/showcontroller/scenv/lib/python3.9/site-packages/PyDMXControl/web/_routes.py", line 17, in <module>
    routes = Blueprint('', __name__, url_prefix='/')
  File "/home/show/showcontroller/scenv/lib/python3.9/site-packages/flask/blueprints.py", line 196, in __init__
    raise ValueError("'name' may not be empty.")
ValueError: 'name' may not be empty.
```

A breaking change in Flask 2.3 is responsible. Due to this you may want to lock down your requirements.txt to specific versions to prevent this in the future.

See #45

**Comment by MattIPv4** [comment]
Open to a PR that locks down the versions for all the libraries in requirements.txt, and also open to a PR that fixes the Flask usage to it is compatible with newer versions :)

**Comment by crscheid** [comment]
Happy to do so. Might be good to just use the latest version of Flask and fix the initialization. I'll take a look later.

**Comment by MattIPv4** [comment]
#53
